### PR TITLE
Make `Pepicon` use async icon components

### PR DESCRIPTION
**Pull request by egoist**
### 1. Generate Vue components for each svg icon to `vue/src/icons/{type}/{name}.ts`, it looks like this:

```ts
// packages/vue/src/icons/print/Airplane.ts
import { defineComponent } from "vue"
import svg from "pepicons/src/icons/print/airplane"
import { baseProps, createSetup } from "../../component"

export default defineComponent({
  name: "PrintAirplane",
  props: {...baseProps},
  setup: createSetup(svg)
})
```

### 2. Export all the icon components in `vue/src/icons/index.ts`:

```ts
// Individual exports, synchronous component
// Only imported components will be bundled
export { default as PrintAirplane } from "./print/Airplane"
export { default as PopAirplane } from "./pop/Airplane"
// ...



// All components, dynamically imported
// All the components will be bundled (in separate chunks) if you import this
// But only the components being used by Vue will be loaded
export const printIcons = {
  airplane: () => import('./print/Airplane'),
  // ...
}

export const popIcons = {
  airplane: () => import('./pop/Airplane'),
  // ...
}

// Same as the old `PepIcon` component
// but internally it will use the `printIcons` and `popIcons`
// to load the icons dynamically
export const PepIcon = defineComponent({})
```

The `packages/vue/src/icons` folder is git ignored.

## Drawbacks

No `umd` build, since it does not support code-splitting, only provide `es` and `cjs` build now.

### CODE REVIEW

**Comment by mesqueeb** [comment]
@egoist the pr looks really good so far!! 🙇🏼‍♂️

**Comment by egoist** [comment]
`pepicons.com` fails to build, should it be migrated to vite?

**Comment by mesqueeb** [comment]
@egoist No! That website is outdated and broken. But I'm having another developer rewrite this on a separate branch right now! ;) So don't worry about the `pepicons.com` please ignore it for now!

If it all works in VitePlay in the `vue` folder, that's good enough for this PR!

**Comment by egoist** [comment]
Then it's ready to be merged now, the only breaking change is it no longer ships a umd bundle

**Pull request merged**
